name: lol-counter-scrapper

on:
  push:
    branches: [ main ]

concurrency: 
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lol-counter-scrapper
          path: |
            dist

  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
        env:
          TF_VAR_cat: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build, terraform]
    steps:
      - name: Download a artifact
        uses: actions/download-artifact@v2
        with:
          name: lol-counter-scrapper
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@1.2.0
        with:
          # Your Cloudflare API Token
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
