name: lol-counter-scrapper

on:
  push:
    branches: [main]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        env:
          DATABASE_USER: lol-counter
          DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
      - name: Generate zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'result.zip'
          exclusions: '*.git* .editorconfig .eslintrc.js .prettierrc package* .vscode/* tsconfig* /*/*.ts README.md /terraform/*' 
      - name: Archive artifacts 2
        uses: actions/upload-artifact@v2
        with:
          name: lol-counter-scrapper
          path: |
            result.zip

  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v2
      - name: az terminal login
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build, terraform]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lol-counter-scrapper
          path: .
      - name: az terminal login
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
      - name: deploy function
        run: |
          az functionapp deployment source config-zip -g lol-counter-scrapper-rg -n lol-counter-scrapper --src result.zip
